--liquibase formatted sql

-- changeset nivethidhas:1007
USE SCHEMA SCH;
CREATE OR REPLACE TABLE TEST_TABLE6
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

--rollback DROP TABLE TEST_TABLE6;

-- changeset nivethidhas:1008
USE SCHEMA SCH;
CREATE OR REPLACE TABLE TEST_TABLE7
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

--rollback DROP TABLE TEST_TABLE7;
